# Generated by Django 5.0.2 on 2024-05-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmodule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='img_num',
            new_name='price',
        ),
    ]
