# Generated by Django 5.0.2 on 2024-05-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmodule', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='p_count',
            field=models.IntegerField(default=None),
        ),
    ]
