# Generated by Django 5.0.2 on 2024-05-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmodule', '0004_cart_p_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='carts',
        ),
    ]
