# Generated by Django 5.0.2 on 2024-05-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmodule', '0005_rename_cart_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
