# Generated by Django 5.0.2 on 2024-05-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmodule', '0009_alter_carts_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='p_id',
        ),
    ]
