# Generated by Django 5.0.2 on 2024-05-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmodule', '0012_products_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='p_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
